### ISSUE TITLE
just installed and got an outdated drupal 9.5.11

### ISSUE THREAD

**Issue by kamazeuci** [YunoHost-Apps/drupal_ynh#106]
Installed Drupal from scratch on my yunohost server, opened it, checked status and got a red warning saying it is an outdated/deprecated version 9.5.11 (from sept 2023), but latest build of yunohost package is from july 2024... So I'm really confused... And it won't update automatically

Thanks

**Comment by tituspijean** [comment]
It looks like the sources are coming from https://github.com/drupal-composer/drupal-project/tree/10.x which should be Drupal 10.

**Comment by kamazeuci** [comment]
It should... But it isn't...

**Comment by kamazeuci** [comment]
![image](https://github.com/user-attachments/assets/8e85d532-d5e4-4d25-9713-a90cca83ef85)

**Comment by kamazeuci** [comment]
@tituspijean or anybody, please let me know if you need more info, logs, whatever. I am really intrigued by this. 
thanks!

**Comment by kamazeuci** [comment]
here is the log of the install 

https://paste.yunohost.org/raw/yepedigoxa

**Comment by kamazeuci** [comment]
on the matrix channel, @OniriCorpe suggests this file https://github.com/YunoHost-Apps/drupal_ynh/blob/master/conf/composer.json needs updating... but I'm not sure what to do

**Comment by kamazeuci** [comment]
@yalh76 you've been poked....

**Comment by OniriCorpe** [comment]
please, don't be too pushy, we're volunteers and harassing us will lead to a warning or a ban

https://yunohost.org/tos

**Comment by kamazeuci** [comment]
I'm terribly sorry!! Didn't mean to. Thought I was helping. I'll let myself breathe and be patient. Thanks for your amazing work.🙏

24 de set. 2024 21:25:48 OniriCorpe ***@***.***>:
