### ISSUE TITLE
Admin account not created successfully on first-time installation

### ISSUE THREAD

**Issue by moghingold** [YunoHost-Apps/drupal_ynh#37]
### Context

- Hardware: VPS
- YunoHost version: 4.2.6.1 (stable)

### Steps to reproduce

   1. Navigate to YOUR.DOMAIN/yunohost/admin/#/apps/install/drupal
   2. Supply an admin password as required
   3. *Click on "Install"
   4. Navigate to newly installed Drupal instance
   5. Attempt to log in with username: admin and the password supplied in step 2

### Actual behavior

The password does not work. Trying to reset the account password for admin reveals an error message that there is no admin account.

### Expected behavior

The user should be logged in as the site admin

### Suggested fix

I think there are two possible ways to address this. Either the admin account can be created successfully with the password specified by the user, or an installation profile with the SSO module pre-installed should be available and the user should be prompted to specify an admin account instead of an admin password during installation.

**Comment by yalh76** [comment]
Can you provide the install logs ?

**Comment by moghingold** [comment]
https://web.moghingold.com/zerobin/?69b324069ca36784#o2pu9Z2jYRW4SFgN9Tt8JaZzNUfpMqY3zf2cwFUodDh

I uninstalled and reinstalled and confirmed that the error still persisted. I can also show you logs for the first installation from earlier today if you'd like.

**Comment by yalh76** [comment]
I've tested and it's working, maybe it comes from the password you chose .... Can you try with a simpler one ?

**Comment by mattbk** [comment]
When I used a password with spaces in it (e.g. "correct horse battery staple"), only the first word was used as the password (e.g., "correct"). The admin username was set as the yunohost "choose an administrator user for this app" username.
