### ISSUE TITLE
Update to Drupal 9.3.5

### ISSUE THREAD

**Issue by JamesClarke7283** [YunoHost-Apps/drupal_ynh#40]
Currently the Drupal version shipped is  8.9.20, which is way behind the stable release and is no longer supported.

For security and stability i recommend updating to Drupal 9.

**Comment by yalh76** [comment]
Feel free to do a PR to upgrade to last Drupal 9 ;)

**Comment by JamesClarke7283** [comment]
### I ran:
`sudo yunohost app upgrade drupal__2 -u https://github.com/YunoHost-Apps/drupal_ynh/tree/9 --debug`

And the upgrade from 8.9.20 to 9.3.5 failed.

### Here is the log:
https://paste.yunohost.org/raw/exuxojapen
