### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/drupal_ynh#44]
### Describe the bug

`Une erreur s'est produite durant l'exécution du script de mise à niveau de l'application`

### Context

- Hardware: *Desktop PC*
- YunoHost version: 4.3.6.2
- I have access to my server: *Full*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- If upgrading, current package version: *8.9.20~ynh1*

### Steps to reproduce

    ```sh
    sudo yunohost app upgrade
    ```

### Expected behavior
Upgrade succeeds.

### Logs

https://paste.yunohost.org/raw/xomevupomu

**Comment by yalh76** [comment]
could you try another upgrade to be sure that's not a one time error

**Comment by stemy2** [comment]
It happens at every attempt.

**Comment by yalh76** [comment]
you should check `/var/www/drupal/drupal/sites/default/settings.php` file.
last line should something like:
`$settings['config_sync_directory'] = 'sites/default/files/config_BLABLABLA...BLABLABLA/sync';`

CF https://www.drupal.org/node/3018145

**Comment by stemy2** [comment]
In my config file, the said line is formed like this:

`$settings['config_sync_directory'] = '/directory/outside/webroot';`

**Comment by yalh76** [comment]
it shouldn't be outside, maybe that's why the upgrade fails

**Comment by stemy2** [comment]
So, where should it be ? And why is an outside location is mentioned ? What should I replace it with?

**Comment by yalh76** [comment]
you should try to add `# ` at the beginning of the line to make it a comment

**Comment by stemy2** [comment]
I commented the line, but upgrade stills failing for the exact same reason.
