### ISSUE TITLE
Upgrade Failed - drupal coder 

### ISSUE THREAD

**Issue by emiliien** [YunoHost-Apps/drupal_ynh#73]
Hi everyone ! i have a little probleme to upgrade my both instance of drupal 

### Describe the bug

Upgrade Failed (drupal) de 9.5.3~ynh1 à 9.5.7~ynh1 . 
It seems have problem with drupal coder

### Context

- Hardware: VM on proxmox 
- YunoHost  11.1.15 (stable)
- I have access to my server: Through SSH | through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no 
  - If yes, please explain:
- Using, or trying to install package version/branch:  (drupal) de 9.5.3~ynh1 à 9.5.7~ynh1 . 

### Steps to reproduce

- *If you used the webadmin, please perform the equivalent command from the CLI first.*

### Expected behavior

*A clear and concise description of what you expected to happen. You can remove this section if the command above is enough to understand your intent.*

### Logs
https://paste.yunohost.org/raw/saqayaviri

**Comment by borisnoyet** [comment]
I had the same error during upgrade of Drupal package from 9.5.3~ynh1 to 9.5.8~ynh1 (here is the last attempt log : https://paste.yunohost.org/raw/ugutiwadin)

First I tried the `git config --global --add safe.directory /var/www/drupal/vendor/drupal/coder`command in the CLI (as root) as mentioned in the debug but the upgrade still failed.

Finally I deleted the "coder" directory in /var/www/drupal/vendor/drupal, `rm -R /var/www/drupal/vendor/drupal/coder` then upgraded again. 
The trick worked. I guess it forced the dependency to be reinstalled a proper way.

**Comment by yalh76** [comment]
seems an upstream issue: https://www.drupal.org/project/coder/issues/3357335

To solve it:
```
rm -R /var/www/drupal/vendor/drupal/coder
```
